const description = [
    {
    id : 1,
    emoji: '😀',
    name: 'Grinning Face',
    meaning: 'General pleasure or good cheer or humour',
    },
    {
    id : 2,
    emoji: '😂',
    name: 'Face with Tears of Joy',
    meaning: 'used to show something funny or pleasing',
    },
    {
    id : 3,
    emoji: '😁',
    name: 'Beaming Face with Smiling Eyes',
    meaning: 'expresses a radiant, gratified happiness. Tone varies, including warm, silly, amused, or proud',
    },
    {
    id : 4,
    emoji: '😍',
    name: 'Smiling Face with Heart-Eyes',
    meaning: 'Often conveys enthusiastic feelings of love, infatuation, and adoration',
    },
    {
    id : 5,
    emoji: '🙂',
    name: 'slightly smiling face',
    meaning: 'patronizing, passive-aggressive, or ironic, as if saying This is fine when it’s really not.',
    },
    {
    id : 6,
    emoji: '😅',
    name: 'Grinning Face with Sweat',
    meaning: 'Intended to depict nerves or discomfort but commonly used to express a close call, as if saying Whew! and wiping sweat from the forehead',
    },
    {
    id : 7,
    emoji: '🙄',
    name: 'Face with Rolling Eyes',
    meaning: 'commonly conveys moderate disdain, disapproval, frustration, or boredom. Tone varies, including playful, sassy, resentful, and sarcastic, as if saying Yeah, whatever.',
    },
    {
    id : 8,
    emoji: '🤣',
    name: 'Rolling on the Floor Laughing',
    meaning: 'Often conveys hysterical laughter more intense ',
    },
    {
    id : 9,
    emoji: '😒',
    name: 'Unamused Face',
    meaning: ' convey a variety of negative emotions, including irritation, displeasure, grumpiness, and skepticism',
    },
    {
    id : 10,
    emoji: '😊',
    name: 'Smiling Face with Smiling Eyes',
    meaning: 'Often expresses genuine happiness and warm, positive feelings',
    },
    {
    id : 11,
    emoji: '😉',
    name: 'Winking Face',
    meaning: ' signal a joke, flirtation, hidden meaning, or general positivity',
    },
    {
    id : 12,
    emoji: '😌',
    name: 'Relieved Face',
    meaning: 'Conveys various pleasant feelings, including contentment, calm, peace, and relief. May also convey feelings of happiness or good-natured humor more generally.',
    },
    {
    id : 13,
    emoji: '😔',
    name: 'Pensive Face',
    meaning: 'convey a variety of sad emotions, including feeling disappointed, hurt, or lonely',
    },
    {
    id : 14,
    emoji: '😃',
    name: 'Smiling Face with Open Mouth',
    meaning: ' Often conveys general happiness and good-natured amusement',
    },
    {
    id : 15,
    emoji: '😄',
    name: 'Smiling Face with Open Mouth and Smiling Eyes',
    meaning: 'Often conveys general happiness and good-natured amusement',
    },
    {
    id : 16,
    emoji: '😆',
    name: 'Smiling Face with Open Mouth and Tightly-Closed Eyes',
    meaning: 'Often conveys excitement or hearty laughter',
    },
    {
    id : 17,
    emoji: '😉',
    name: 'Winking Face',
    meaning: ' signal a joke, flirtation, hidden meaning, or general positivity. Tone varies, including playful, affectionate, suggestive, or ironic.',
    },
    {
    id : 18,
    emoji: '😋',
    name: 'Face Savoring Food',
    meaning: 'Widely used to convey that a food item is delicious. May also express that a person is attractive or that something is enjoyable',
    },
    {
    id : 19,
    emoji: '😎',
    name: 'Smiling Face with Sunglasses',
    meaning: 'Often used to convey the slang sense of cool. May also express a confident, carefree attitude or that something is excellent',
    },
    {
    id : 20,
    emoji: '😏',
    name: 'Smiling Face with Smirking Eyes',
    meaning: 'Often used to convey flirtation or sexual innuendo',
    },
    {
    id : 21,
    emoji: '😘',
    name: 'Face Blowing a Kiss',
    meaning: 'May represent a kiss goodbye or good night and convey feelings of love and affection more generally',
    },
    {
    id : 22,
    emoji: '😜',
    name: 'Winking Face with Tongue',
    meaning: 'Often conveys a sense of fun, excitement, wackiness, buffoonery, or joking around',
    },
    {
    id : 23,
    emoji: '😝',
    name: 'Squinting Face with Tongue',
    meaning: 'Often conveys a sense of fun, excitement, playfulness, hilarity, and happiness, as if saying Squee! or Awesome!',
    },
    {
    id : 24,
    emoji: '😛',
    name: 'Face with Tongue',
    meaning: 'Can variously convey a sense of fun, excitement, silliness, cuteness, happiness, or jesting, as if saying Just kidding!',
    },
    {
    id : 25,
    emoji: '😳',
    name: 'Blushed Face',
    meaning: 'Intended to depict such feelings as embarrassment, but meaning very widely varies. Other senses include flattery, surprise, disbelief, admiration, affection, and excitement',
    },
    {
    id : 26,
    emoji: '😱',
    name: 'Face Screaming in Fear',
    meaning: 'While intended to represent horror and fright, it commonly conveys such feelings as shock, awe, disbelief, and intense excitement, as a screaming fan.',
    },
    {
    id : 27,
    emoji: '😨',
    name: 'Fearful Face',
    meaning: 'While intended to represent fear (less intense than 😱 Face Screaming in Fear), it also conveys a wide variety of emotions, including feeling amazed, shocked, sad, upset, and cold',
    },
    {
    id : 28,
    emoji: '😰',
    name: 'Anxious Face with Sweat',
    meaning: 'Meaning widely varies, but commonly conveys such feelings as sadness, disappointment, fear, and anxiety',
    },
    {
    id : 29,
    emoji: '😥',
    name: 'Sad but Relieved Face',
    meaning: 'Commonly conveys mild degrees of frustration and sadness',
    },
    {
    id : 30,
    emoji: '😓',
    name: 'Downcast Face with Sweat',
    meaning: 'Meaning widely varies, but commonly conveys a moderate degree of sadness, pain, frustration, or disappointment',
    },
    {
    id : 31,
    emoji: '😭',
    name: 'Loudly Crying Face',
    meaning: '',
    },
    {
    id : 32,
    emoji: '😢',
    name: 'Crying Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 33,
    emoji: '🥰',
    name: 'smiling face with three hearts',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 34,
    emoji: '🤗',
    name: 'Hugging Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 35,
    emoji: '🤩',
    name: 'Smiling Face with Starry Eyes',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 36,
    emoji: '🤔',
    name: 'Thinking Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 38,
    emoji: '🤭',
    name: 'Face with Hand Over Mouth',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 39,
    emoji: '🤫',
    name: 'Shushing Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 40,
    emoji: '🤥',
    name: 'Lying Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 41,
    emoji: '🤐',
    name: 'Zipper-Mouth Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 42,
    emoji: '🤨',
    name: 'Face with one eyebrow raised',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 43,
    emoji: '🤬',
    name: 'Swearing Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 44,
    emoji: '🤯',
    name: 'Exploding Head',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 45,
    emoji: '🤠',
    name: 'Smiling Face with Cowboy Hat',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 46,
    emoji: '🤡',
    name: 'Clown Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 47,
    emoji: '🤮',
    name: 'Vomiting Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 48,
    emoji: '🤧',
    name: 'Sneezing Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 49,
    emoji: '🤢',
    name: 'Nauseated Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 50,
    emoji: '🤕',
    name: 'Face with Head-Bandage',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 51,
    emoji: '🤑',
    name: 'Money-Mouth Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 52,
    emoji: '🤓',
    name: 'Nerd Face',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 53,
    emoji: '🫣',
    name: 'Smiling Face with Heart-Eyes',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 54,
    emoji: '🫢',
    name: 'Hand over mouth',
    meaning: 'This represents a smiling face with heart-eyes',
    },
    {
    id : 55,
    emoji: '🥸',
    name: 'Disguised face',
    meaning: 'This represents a smiling face with heart-eyes',
    },

]
export default description;